# Generated by Django 6.0.3 on 2026-03-30 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loadtest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('latency_spike', 'Latency Spike'), ('high_error_rate', 'High Error Rate'), ('throughput_drop', 'Throughput Drop'), ('general', 'General Anomaly')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('score', models.FloatField(help_text='Anomaly score (higher = more anomalous)')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('metric_value', models.FloatField(help_text='The metric value that triggered detection')),
                ('threshold_value', models.FloatField(help_text='The threshold that was exceeded')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='loadtest.loadtestresult')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latency_ms', models.FloatField()),
                ('throughput_rps', models.FloatField()),
                ('error_rate', models.FloatField()),
                ('request_index', models.PositiveIntegerField(default=0)),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='loadtest.loadtestresult')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('load_level', models.PositiveIntegerField(help_text='Simulated concurrent users')),
                ('predicted_latency_ms', models.FloatField()),
                ('predicted_error_rate', models.FloatField()),
                ('failure_probability', models.FloatField(default=0.0, help_text='Probability of failure (0–1)')),
                ('confidence_score', models.FloatField(default=0.0)),
                ('model_version', models.CharField(default='v1', max_length=50)),
                ('test_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='loadtest.loadtestresult')),
            ],
            options={
                'ordering': ['-predicted_at'],
            },
        ),
    ]
