# Generated by Django 6.0.3 on 2026-03-30 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoadTestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], default='GET', max_length=10)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('body', models.JSONField(blank=True, null=True)),
                ('request_count', models.PositiveIntegerField(default=10)),
                ('concurrency', models.PositiveIntegerField(default=1)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoadTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('successful_requests', models.PositiveIntegerField(default=0)),
                ('failed_requests', models.PositiveIntegerField(default=0)),
                ('avg_latency_ms', models.FloatField(default=0.0)),
                ('min_latency_ms', models.FloatField(default=0.0)),
                ('max_latency_ms', models.FloatField(default=0.0)),
                ('p50_latency_ms', models.FloatField(default=0.0)),
                ('p95_latency_ms', models.FloatField(default=0.0)),
                ('p99_latency_ms', models.FloatField(default=0.0)),
                ('throughput_rps', models.FloatField(default=0.0)),
                ('error_rate', models.FloatField(default=0.0)),
                ('status_codes', models.JSONField(default=dict)),
                ('raw_latencies', models.JSONField(default=list)),
                ('error_messages', models.JSONField(default=list)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='loadtest.loadtestconfig')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
